insert into public.books_authorprofile (website, biography, author_id) values ('http://example.com', 'Curabitur nec lacus elit. Aenean euismod.', 1);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.org', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 2);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.net', 'Phasellus ac ligula nec leo cursus tristique.', 3);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.info', 'Donec lacinia tortor vel orci ultricies pretium.', 4);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.co.uk', 'Suspendisse potenti. Ut fermentum eros nec elit tempor.', 5);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.ca', 'Maecenas vestibulum quam vitae felis dignissim, id tempus arcu.', 6);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.fr', 'Vestibulum ante ipsum primis in faucibus orci luctus.', 7);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.de', 'Integer consectetur orci nec mauris tincidunt vehicula.', 8);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.it', 'Fusce vitae est id augue faucibus eleifend non ut elit.', 9);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.au', 'Etiam congue erat eget lorem scelerisque, in scelerisque nulla.', 10);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.jp', 'Sed ut risus eu ligula pellentesque fermentum.', 11);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.cn', 'Nam venenatis nisi vel sapien pulvinar accumsan.', 12);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.ru', 'Ut convallis odio eu metus sagittis, sit amet scelerisque velit.', 13);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.br', 'Aliquam malesuada urna non augue venenatis malesuada.', 14);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.mx', 'Cras id purus nec felis sodales elementum nec a lorem.', 15);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.ar', 'Quisque a nibh sed dolor malesuada vehicula.', 16);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.za', 'Nullam quis ipsum sit amet dolor suscipit viverra.', 17);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.ng', 'Mauris interdum nulla a risus accumsan, quis lacinia lorem.', 18);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.kr', 'Nunc ultricies magna nec mi ullamcorper, non scelerisque erat.', 19);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.sa', 'Praesent sodales risus nec nisi bibendum volutpat.', 20);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.id', 'Aenean sit amet ex vitae eros laoreet laoreet.', 21);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.pk', 'Suspendisse nec lorem nec urna varius pellentesque.', 22);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.eg', 'Integer vulputate justo in erat sagittis tristique.', 23);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.tr', 'In nec risus at nisi pharetra tristique.', 24);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.in', 'Etiam et dui id libero gravida pellentesque nec id magna.', 25);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.my', 'Sed interdum justo sed ligula fermentum, in consequat sapien.', 26);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.sg', 'Pellentesque non felis auctor, elementum odio nec, lobortis nisi.', 27);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.hk', 'Vivamus tempor ligula ac lacus auctor scelerisque.', 28);
insert into public.books_authorprofile (website, biography, author_id) values ('https://example.th', 'Ut eu purus eu erat congue eleifend non sed massa.', 29);
insert into public.books_authorprofile (website, biography, author_id) values ('http://example.vn', 'Donec ac sem sit amet nisi pulvinar condimentum.', 30);
