insert into public.books_book (title, publication_date, publisher_id) values ('Tarzan the Fearless', '2012-01-16', 2);
insert into public.books_book (title, publication_date, publisher_id) values ('Why Man Creates', '2013-08-14', 7);
insert into public.books_book (title, publication_date, publisher_id) values ('All Relative', '2018-04-18', 1);
insert into public.books_book (title, publication_date, publisher_id) values ('Caught', '2016-12-01', 6);
insert into public.books_book (title, publication_date, publisher_id) values ('Pacific Rim', '2018-11-30', 15);
insert into public.books_book (title, publication_date, publisher_id) values ('Dragonfly', '2024-04-07', 14);
insert into public.books_book (title, publication_date, publisher_id) values ('Fright Night Part II', '2016-03-31', 12);
insert into public.books_book (title, publication_date, publisher_id) values ('You Can''t Win ''Em All', '2021-08-12', 4);
insert into public.books_book (title, publication_date, publisher_id) values ('Mr. Blandings Builds His Dream House', '2010-12-14', 10);
insert into public.books_book (title, publication_date, publisher_id) values ('Chicago', '2017-01-31', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Minuscule: Valley of the Lost Ants (Minuscule - La vallée des fourmis perdues)', '2024-05-14', 15);
insert into public.books_book (title, publication_date, publisher_id) values ('Sketches of Frank Gehry', '2024-09-16', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Eagle vs Shark', '2012-02-21', 11);
insert into public.books_book (title, publication_date, publisher_id) values ('Creepshow 2', '2012-01-12', 15);
insert into public.books_book (title, publication_date, publisher_id) values ('Wartorn: 1861-2010', '2019-09-20', 3);
insert into public.books_book (title, publication_date, publisher_id) values ('Three Ages', '2019-06-02', 4);
insert into public.books_book (title, publication_date, publisher_id) values ('Gold Diggers: The Secret of Bear Mountain', '2020-03-01', 12);
insert into public.books_book (title, publication_date, publisher_id) values ('At Sea', '2014-06-08', 12);
insert into public.books_book (title, publication_date, publisher_id) values ('Crude', '2017-10-22', 3);
insert into public.books_book (title, publication_date, publisher_id) values ('Relative Strangers', '2024-08-10', 5);
insert into public.books_book (title, publication_date, publisher_id) values ('Emmanuel''s Gift', '2024-01-12', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Asphalt Playground (La cité rose)', '2024-10-22', 3);
insert into public.books_book (title, publication_date, publisher_id) values ('Few of Us', '2013-05-02', 11);
insert into public.books_book (title, publication_date, publisher_id) values ('Inside Job', '2019-06-22', 13);
insert into public.books_book (title, publication_date, publisher_id) values ('Huhwihaji Anha (No Regret)', '2019-04-08', 10);
insert into public.books_book (title, publication_date, publisher_id) values ('Joshua', '2013-11-30', 12);
insert into public.books_book (title, publication_date, publisher_id) values ('Fall of the House of Usher, The (House of Usher)', '2018-02-24', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Place Called Chiapas, A', '2012-01-18', 11);
insert into public.books_book (title, publication_date, publisher_id) values ('Investigation of a Citizen Above Suspicion (Indagine su un cittadino al di sopra di ogni sospetto)', '2013-12-03', 7);
insert into public.books_book (title, publication_date, publisher_id) values ('High Time (Big Daddy)', '2015-07-20', 11);
insert into public.books_book (title, publication_date, publisher_id) values ('Dear Diary (Caro Diario)', '2024-07-13', 4);
insert into public.books_book (title, publication_date, publisher_id) values ('Ted Bundy', '2013-12-25', 5);
insert into public.books_book (title, publication_date, publisher_id) values ('Hannibal Rising', '2019-03-31', 5);
insert into public.books_book (title, publication_date, publisher_id) values ('Touchback', '2019-10-11', 1);
insert into public.books_book (title, publication_date, publisher_id) values ('Working Girl', '2014-11-21', 14);
insert into public.books_book (title, publication_date, publisher_id) values ('Kisses for My President', '2012-10-25', 5);
insert into public.books_book (title, publication_date, publisher_id) values ('Fright Night', '2013-11-16', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Lie with Me', '2023-04-15', 3);
insert into public.books_book (title, publication_date, publisher_id) values ('Forgotten One, The', '2023-01-18', 3);
insert into public.books_book (title, publication_date, publisher_id) values ('Silent Running', '2014-01-15', 11);
insert into public.books_book (title, publication_date, publisher_id) values ('Cellar, The (Huset vid vägens ände)', '2011-11-23', 13);
insert into public.books_book (title, publication_date, publisher_id) values ('Salting the Battlefield', '2012-03-15', 5);
insert into public.books_book (title, publication_date, publisher_id) values ('Spirit Trap', '2015-05-08', 2);
insert into public.books_book (title, publication_date, publisher_id) values ('Small Town Gay Bar', '2019-07-20', 4);
insert into public.books_book (title, publication_date, publisher_id) values ('Torment (Hets)', '2022-10-10', 13);
insert into public.books_book (title, publication_date, publisher_id) values ('Spook Who Sat by the Door, The', '2017-05-06', 6);
insert into public.books_book (title, publication_date, publisher_id) values ('Hurry Sundown', '2012-09-29', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Situation, The', '2012-06-11', 13);
insert into public.books_book (title, publication_date, publisher_id) values ('Paper Will Be Blue, The (Hîrtia va fi albastrã)', '2019-09-25', 10);
insert into public.books_book (title, publication_date, publisher_id) values ('The Land Before Time XII: The Great Day of the Flyers', '2012-09-04', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Business as Usual', '2024-07-20', 14);
insert into public.books_book (title, publication_date, publisher_id) values ('Murder à la Mod', '2015-11-05', 6);
insert into public.books_book (title, publication_date, publisher_id) values ('Boricua''s Bond', '2016-09-09', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('In the Cut', '2021-03-31', 8);
insert into public.books_book (title, publication_date, publisher_id) values ('Mercy', '2016-02-20', 9);
insert into public.books_book (title, publication_date, publisher_id) values ('Apple, The (Sib)', '2023-12-28', 7);
insert into public.books_book (title, publication_date, publisher_id) values ('Snowblind', '2014-04-22', 1);
insert into public.books_book (title, publication_date, publisher_id) values ('Godzilla vs. Megalon (Gojira tai Megaro)', '2011-02-06', 7);
insert into public.books_book (title, publication_date, publisher_id) values ('Tai Chi Zero', '2016-06-27', 2);
insert into public.books_book (title, publication_date, publisher_id) values ('Club Sandwich', '2012-03-25', 3);
